# Generated by Django 3.0 on 2019-12-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('cn_official_price', models.IntegerField(default=0)),
                ('pic', models.CharField(default='', max_length=1024)),
                ('other_people_price', models.CharField(default='', max_length=255)),
                ('hk_official_price', models.IntegerField(default=0)),
                ('our_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('sell_person', models.CharField(default='', max_length=255)),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item_record', to='checkprice.Item')),
            ],
        ),
    ]
